baseURL: "/"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blogs
    #   weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  staticPath: "https://arnavkar.github.io/my-site/"  # The path to serve the static files from

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "images/spec.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Arnav Shirodkar."
    subtitle: "I'm a Software Developer"
    content: "Percussionist, Composer and Music Tech enthusiast"
    image: "/images/me.jpeg"
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume/CV"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Arnavkar
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/arnav-shirodkar/

  # About
  about:
    enable: true
    title: "About Me"
    image: /images/me2.jpeg
    content: |-
      I am a software developer from Singapore with a passion for exploring the intersection of music and technology. I also have a strong background in percussion performance and electronic music.

      I am currently working on my Senior Project, a symbolic music transformer model for real-time improvisation alongside a live performer.
      Built with MaxMSP, Node.js and Typescript for the performer interface, Python and Tensorflow/ Pytorch for the transformer model."	
      
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "PyTorch"
        - "Typescript"
        - "Shiny (R)"
        - "Max/MSP"
        - "Tensorflow"
        - "TidalCycles"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Undergraduate Researcher"
        company: "AIICE"
        companyUrl: "https://identityincs.org/"
        date: "Jan 2023 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://aiice.shinyapps.io/AiiCE/"
        info:
          enable: false
        content: |
          I'm currently working on a research project with Prof. Valerie Barr as part of an NSF-funded Alliance for Identity Inclusive Computing Education (AIICE) project to analyze CS degree completions for intersectional identities across all Title-IV institutions in the U.S.

          - Designed and implemented a Python data scraper as well as an interactive web app with R to show trends in degree completions with ggplot2, handling upwards of 10 million data points across 20 categories using dplyr and meeting web accessibility standards.
          - Built an automated workflow with Bash and Python to seamlessly test and integrate data scraping, cleaning, processing and Shiny app deployment for data released in subsequent years

      - job: "Software Engineer Intern"
        company: "Morningstar"
        companyUrl: "https://www.morningstar.com/"
        date: "Jun 2022 - Oct 2022"
        info:
          enable: false
        content: |
          - Worked with research and quant team to lead the migration of outdated data quality tests to Morningstar’s new data quality framework, improving test coverage for updated data schemas to 100% and improving test execution times by 20%
          - Contributed changes to Great Expectations (v2), an open source data quality framework, adding support for pairwise data column testing for SQLAlchemy backends.
          - Deployed a new AWS pipeline in Morningstar’s Data-Lake Eventing framework (Athena, SES, SQS) using Docker, Jenkins, Typescript and Splunk-On-Call to detect and report critical test failures to data producers, improving failure response times by 40% for ~ 15 teams
        
      - job: "Software Engineer Intern"
        company: "Soundbrenner"
        companyUrl: "https://www.soundbrenner.com/blog/"
        date: "Mar 2022 - Jun 2022"
        info:
          enable: false
        content: |
          - Led early development of a new in-app chromatic tuner by analyzing user statistics and community engagement forums for company’s iOS app before proposing the new feature, enhancing product usability for 30% of the customer base 
          - Created a rich tuner design with multiple controllers, custom components and reactivity across various device screen sizes using Swift and iOS storyboards for a cohesive user experience
          - Implemented real-time pitch detection using signal autocorrelation and iOS Core Audio,  maintaining original dependencies to ensure backwards compatibility with iOS 7.0 and above. 

      - job: "Junior Developer"
        company: "Musiio"
        companyUrl: "https://www.musiio.com/"
        date: "June 2017 - Nov 2019"
        info:
          enable: true
          content: Musiio has since been acquired by Soundcloud
        content: |
          - Built a full-stack dashboard with React, Flask and SQLAlchemy for Musiio’s assistance in Vans’s “Musicians Wanted” competition, tracking 4000 song submissions from hundreds of artists across 13 countries
          - Improved the efficiency of internal Python scripting with data aggregation, multi-threading and caching: 33% faster YouTube audio tagging, 75% fewer requests to Spotify API
          - Delivered 30+ high-value client POCs worth several thousand dollars in revenue, including Universal Music, CDBaby, Hipgnosis, Soundcloud 

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "B.A. Computer Science & B.M. Percussion Performance"
        school:
          name: "Bard College & Conservatory"
          url: "https://www.bard.edu/"
        date: "2019 - 2024"
        GPA: "3.95 / 4.00"
        content: |
          Extracurricular Activities:
            - One of 3 Founders of the Bard Computer Science Club
            - Captain for Bard's Ultimate Frisbee Team

      - title: "High School"
        school:
          name: "National Junior College (Singapore)"
          url: "https://www.nationaljc.moe.edu.sg/"
        content: |
          A-Level Subjects:
            - H2 Mathematics
            - H2 Physics
            - H2 Chemistry
            - H2 Music

          A-Level Score: 90/90
  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Distinguished Scientist Scholarship
        content: Receipient of the Distinguished Scientist Scholarship from Bard College

      - title: John W. Boylan Scholar in Medicine and Science
        content: Receipient of the John W. Boylan Scholar in Medicine and Science from Bard College

      - title: Morningstar Tech Case Study Winner
        content: In a team of 5, developed an interactive trading simulation that tracks user behavior to measure indicators of investor overconfidence

      - title: Techstars Startup Weekend Runner Up
        content: Pitched an idea for an AI based cybersecurity startup to a panel of judges and investors, winning 2nd place out of 9 teams

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Real-Time Music Transformer
        content: A symbolic music transformer model for real-time improvisation alongside a live performer. 
        image: /images/robotImprovisor.png
        badges:
          - "Node.js"
          - "Typescript"
          - "PyTorch"
          - "Tensorflow/ Tensorflow.js"
          - "Max/MSP"

        links:
          - icon: fab fa-github
            url: https://github.com/Arnavkar

      - title: TSP Path Visualizer
        content: Created an animated path visualizer for the TSP problem with greedy and genetic algorithm solutions
        image: /images/tsp.png
        badges:
          - "Python"
          - "Matplotlib"
        links:
          - icon: fab fa-github
            url: https://github.com/Arnavkar/TSP_Project

      - title: Music Meter Classifier
        content: Designed an end-to-end musical meter classifier using CNNs that inferred rhythmic groupings from mel-spectrogram data in Tensorflow, achieving 73% accuracy
        image: /images/spec.png
        badges:
          - "Python"
          - "Tensorflow"
          - "Librosa"
          - "Numpy"
        links:
          - icon: fab fa-github
            url: https://github.com/Arnavkar/Music_Meter_Classifier

      - title: Green Bean
        content: Prototyped a hybrid-native mobile application that provides users with sustainability information for grocery items leveraging barcode scanning libraries built by Scandit, encouraging sustainable grocery purchases.
        image: /images/greenbean.png
        badges:
          - "Vue"
          - "Javascript"
          - "Cordova"
          - "Scandit"
          - "Quasar"
        links:
          - icon: fab fa-github
            url: https://github.com/Arnavkar/Project_Headstart

      - title: BackBend
        content: Prototyped a mobile application for a hackathon that uses mobile device cameras to monitor and pings users with bad posture while they work.
        image: /images/backpain.jpg
        badges:
          - "Tensorflow.js"
          - "PoseNet"
          - "Flutter"
        links:
          - icon: fab fa-github
            url: https://github.com/Arnavkar/BackBend_Posture-Detection

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Feel free to reach out to me for any opportunities or collaborations!
    email: arnavshirodkar@gmail.com
    btnName: Email me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    socialNetworks:
      github: https://github.com/Arnavkar
      linkedin: https://www.linkedin.com/in/arnav-shirodkar/
      instagram: https://www.instagram.com/coding_percussionist/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: true

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>